- name: Enable ASLR
  sysctl:
    name: kernel.randomize_va_space
    value: '2'
    state: present
    reload: yes

- name: Disable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '0'
    state: present
    reload: yes

- name: Disable ICMP redirects
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: '0'
    state: present
    reload: yes

- name: Ignore ICMP broadcast requests
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: '1'
    state: present
    reload: yes

- name: Enable SYN cookies
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: '1'
    state: present
    reload: yes

- name: Log Martian packets
  sysctl:
    name: net.ipv4.conf.all.log_martians
    value: '1'
    state: present
    reload: yes

- name: Disable source routing
  sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: '0'
    state: present
    reload: yes

- name: Apply all sysctl changes
  command: sysctl -p
